### ISSUE TITLE
アプリアイコンの画像ファイルってどれですか？

### ISSUE THREAD

**Issue by uehara1414** [uehara1414/kuso-wifi-button#10]
私がパッケージングして配布します

**Comment by defaultcf** [comment]
プルリク送ります

**Comment by uehara1414** [comment]
待ってます！

**Comment by uehara1414** [comment]
押し間違えて閉じちゃいました

ぷっるりく待ってます！

**Comment by defaultcf** [comment]
送ったよ...?

**Comment by defaultcf** [comment]
というかpackageし直しました。ご確認ください。めちゃ軽です。
やっぱ間違ってたんだな。

**Comment by uehara1414** [comment]
アイコンファイルがどれか教えてください
パッケージ方法をREADMEに書きます

**Comment by defaultcf** [comment]
あ、そういう...

| OS | Icon File |
| --- | --- |
| Mac | src/poowifi.icns |
| Win | src/poowifi.ico |
| Linux | src/poowifi.png |

**Comment by uehara1414** [comment]
thx
