### ISSUE TITLE
リリースされたアプリに不備がある

### ISSUE THREAD

**Issue by uehara1414** [uehara1414/kuso-wifi-button#6]
- [x] ポストがうまくいっていない( サーバーに反映されない )

- [x] MacOS 用のバイナリしかない

**Comment by defaultcf** [comment]
手元のelectronコマンドで立ち上げたら上手くいって、バイナリファイルにすると上手くいかない。config moduleの使用に問題があるかも。

**Comment by defaultcf** [comment]
直に書くことで解決した。
