### ISSUE TITLE
連打すると回線良好なのに不通として送信されるケースがある。

### ISSUE THREAD

**Issue by b4h0-c4t** [uehara1414/kuso-wifi-button#8]
連打を想定していないのであれば、そのような設計にしてはどうでしょうかね

**Comment by defaultcf** [comment]
非同期処理と格闘中なの💢

**Comment by uehara1414** [comment]
もしかしたら実際に繋がってないのかも
本学のwifi、瞬間的に繋がらなくなることが結構ある気がする

**Comment by defaultcf** [comment]
コード見直したけど、非同期処理は上手くやってたわ
@uehara1414 の言う通り、本当に繋がっていない可能性ある

**Comment by b4h0-c4t** [comment]
hkrk-wifiと自宅のwifiで実験してみましょう
(一体何レコなんだ...)

**Comment by uehara1414** [comment]
hkrk-wifi...
今日自宅で試してみます

**Comment by b4h0-c4t** [comment]
ダウンロードと並行して稼働してみましたが、DLプログレスが順調に進む中、19/25のクソWiFi判定が「不通」となっていた。(DLの関係で速度が遅くなった可能性も考えられる。)

**Comment by uehara1414** [comment]
それはプログラム側がのバグっぽいなぁ
要修正だわ

**Comment by defaultcf** [comment]
本プログラムは8.8.8.8へのpingの応答時間を利用していることから以上のような「不通」問題が発生すると思われ。
他に良い案があったら、どうぞ。

**Comment by b4h0-c4t** [comment]
一番初めに提案したけど、連打制限をかけるのが一番良いと思われ

**Comment by defaultcf** [comment]
連打の制限は全く考えていません。

**Comment by b4h0-c4t** [comment]
連打制限というより、一度押されたら100ms程度のdelayを置くくらいで良いと思いますが

**Comment by uehara1414** [comment]
一度のボタン押下ごとに、数回pingを送って平均もしくは一番早かったものを適用するようにするようにしたら、より正確な値が出せるし、事故も減りそう。
その代わりに、計測は数秒に１回にして、それよりも短いタイミングでボタンが押されたときはそれらをまとめて同じpingの値をつかうようにしたらどうだろうか。

**Comment by defaultcf** [comment]
今回の事象は連打時のものだし、正直サーバ側で選別すれば良いのではと思ってしまう。

**Comment by b4h0-c4t** [comment]
delay置くだけならアプリ側で弄ったほうが見栄え的にいいのでは？
連打したのに数回しか転送されてないとかissue投げられそうですし
